##############################################################################
# Copyright 2022-2025 Leon Lynch
#
# This file is licensed under the terms of the LGPL v2.1 license.
# See LICENSE file.
##############################################################################

name: Fedora build

on: [push]

jobs:
  build-fedora-debug:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: "Fedora 41", fedora_version: 41, deps: "none", build_emv_tool: NO, build_emv_viewer: NO }
          - { name: "Fedora 41", fedora_version: 41, deps: "pcsclite/qt", build_emv_tool: YES, build_emv_viewer: YES }
          - { name: "Fedora 42", fedora_version: 42, deps: "pcsclite/qt", build_emv_tool: YES, build_emv_viewer: YES }

    name: ${{ matrix.name }} build (static/debug/${{ matrix.deps }})
    runs-on: ubuntu-latest
    container: fedora:${{ matrix.fedora_version }}

    steps:
    - name: Install build tools and dependencies
      run: sudo dnf -y install git cmake gcc g++ mbedtls-devel boost-devel iso-codes-devel json-c-devel

    - name: Install PCSCLite
      if: contains(matrix.deps, 'pcsclite')
      run: sudo dnf -y install pcsc-lite-devel

    - name: Install Qt5
      if: contains(matrix.deps, 'qt')
      run: sudo dnf -y install qt5-qtbase-devel

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # Container user doesn't match runner user
    # Github has only fixed https://github.com/actions/checkout/issues/760
    # not https://github.com/actions/checkout/issues/766
    - name: Configure Git
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git describe --always --dirty

    - name: Configure CMake
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE="Debug" \
          -DBUILD_EMV_DECODE=YES \
          -DBUILD_EMV_TOOL=${{ matrix.build_emv_tool }} \
          -DBUILD_EMV_VIEWER=${{ matrix.build_emv_viewer }}

    - name: Build
      run: cmake --build build -j 4

    - name: Test
      run: ctest --test-dir build -j 4 --output-on-failure

  build-fedora-release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: "Fedora 41", fedora_version: 41 }
          - { name: "Fedora 42", fedora_version: 42 }

    name: ${{ matrix.name }} release
    runs-on: ubuntu-latest
    container: fedora:${{ matrix.fedora_version }}

    steps:
    - name: Install build tools and dependencies
      run: |
        sudo dnf -y install git gh cmake gcc g++ mbedtls-devel boost-devel iso-codes-devel json-c-devel pcsc-lite-devel bash-completion-devel doxygen rpm-build qt5-qtbase-devel

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    # Container user doesn't match runner user
    # Github has only fixed https://github.com/actions/checkout/issues/760
    # not https://github.com/actions/checkout/issues/766
    - name: Configure Git
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git describe --always --dirty

    - name: Get version from git tag
      run: echo "GIT_DESCRIBE=$(git describe --always --dirty)" >> $GITHUB_ENV

    - name: Configure CMake
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE="RelWithDebInfo" \
          -DCMAKE_INSTALL_PREFIX=/usr \
          -DBUILD_SHARED_LIBS=YES \
          -DBUILD_DOCS=YES \
          -DBUILD_EMV_DECODE=YES \
          -DBUILD_EMV_TOOL=YES \
          -DBUILD_EMV_VIEWER=YES \
          -DCPACK_COMPONENTS_GROUPING=ALL_COMPONENTS_IN_ONE

    - name: Build
      run: cmake --build build -j 4

    - name: Test
      run: ctest --test-dir build -j 4 --output-on-failure

    - name: Package
      run: cmake --build build --target package

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: emv-utils-${{ env.GIT_DESCRIBE }}-fedora${{ matrix.fedora_version }}
        path: build/emv-utils-*.rpm
        if-no-files-found: error
