##############################################################################
# Copyright 2022-2025 Leon Lynch
#
# This file is licensed under the terms of the LGPL v2.1 license.
# See LICENSE file.
##############################################################################

name: Windows build

on: [push]

jobs:
  build-windows-msys2-debug:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - { sys: mingw64, env: x86_64, build_type: "Release", lib_type: "static", shared_libs: "NO", deps: "none", fetch_deps: NO, build_emv_tool: NO, build_emv_viewer: NO }
          - { sys: mingw64, env: x86_64, build_type: "Debug", lib_type: "dll", shared_libs: "YES", deps: "qt6", fetch_deps: NO, build_emv_tool: YES, build_emv_viewer: YES }
          - { sys: mingw64, env: x86_64, build_type: "Release", lib_type: "static", shared_libs: "NO", deps: "qt5", fetch_deps: YES, build_emv_tool: YES, build_emv_viewer: YES }
          - { sys: ucrt64, env: ucrt-x86_64, build_type: "Debug", lib_type: "static", shared_libs: "NO", deps: "qt5", fetch_deps: NO, build_emv_tool: YES, build_emv_viewer: YES }
          - { sys: ucrt64, env: ucrt-x86_64, build_type: "Release", lib_type: "dll", shared_libs: "YES", deps: "qt6", fetch_deps: YES, build_emv_tool: YES, build_emv_viewer: YES }
          # NOTE: Only test Qt6 for clang64 because Qt5's windeployqt does not support clang64
          - { sys: clang64, env: clang-x86_64, build_type: "Debug", lib_type: "static", shared_libs: "NO", deps: "qt6", fetch_deps: NO, build_emv_tool: YES, build_emv_viewer: YES }
          - { sys: clang64, env: clang-x86_64, build_type: "Release", lib_type: "dll", shared_libs: "YES", deps: "qt6", fetch_deps: YES, build_emv_tool: YES, build_emv_viewer: YES }

    name: Windows MSYS2 ${{matrix.sys}} build (${{ matrix.lib_type }}/${{ matrix.build_type }}/${{ matrix.deps }})

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSYS2 ${{matrix.sys}}
      uses: msys2/setup-msys2@v2
      with:
        release: false
        msystem: ${{matrix.sys}}
        install: >-
          base-devel
          git
          mingw-w64-${{matrix.env}}-toolchain
          mingw-w64-${{matrix.env}}-cmake
          mingw-w64-${{matrix.env}}-ninja
          mingw-w64-${{matrix.env}}-boost
          mingw-w64-${{matrix.env}}-iso-codes
          mingw-w64-${{matrix.env}}-json-c
          mingw-w64-${{matrix.env}}-gettext

    - name: Install MbedTLS
      if: ${{ matrix.fetch_deps == 'NO' }}
      run: |
        pacman --noconfirm -S --needed mingw-w64-${{matrix.env}}-mbedtls
        echo "CMAKE_REQUIRE_FIND_PACKAGE_MbedTLS=YES" >> $GITHUB_ENV

    - name: Install Qt5
      if: contains(matrix.deps, 'qt5')
      run: |
        pacman --noconfirm -S --needed mingw-w64-${{matrix.env}}-qt5-base mingw-w64-${{matrix.env}}-qt5-tools

    - name: Install Qt6
      if: contains(matrix.deps, 'qt6')
      run: |
        pacman --noconfirm -S --needed mingw-w64-${{matrix.env}}-qt6-base mingw-w64-${{matrix.env}}-qt6-tools

    # MSYS2 Git assumes CRLF by default
    - name: Configure Git
      run: |
        git config --global core.autocrlf true
        git describe --always --dirty

    - name: Configure CMake
      run: |
        cmake -G Ninja -B build \
          -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}" \
          -DBUILD_SHARED_LIBS=${{ matrix.shared_libs }} \
          -DFETCH_MBEDTLS=${{ matrix.fetch_deps }} \
          -DCMAKE_REQUIRE_FIND_PACKAGE_MbedTLS=${{ env.CMAKE_REQUIRE_FIND_PACKAGE_MbedTLS }} \
          -DFETCH_ARGP=YES \
          -DBUILD_EMV_DECODE=YES \
          -DBUILD_EMV_TOOL=${{ matrix.build_emv_tool }} \
          -DBUILD_EMV_VIEWER=${{ matrix.build_emv_viewer }}

    - name: Build
      run: cmake --build build -j 4

    - name: Test
      run: ctest --test-dir build -j 4 --output-on-failure

  build-windows-msys2-release:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - { sys: mingw64, env: x86_64, build_type: "RelWithDebInfo" }

    name: Windows MSYS2 ${{matrix.sys}} build (release)

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Setup MSYS2 ${{matrix.sys}}
      uses: msys2/setup-msys2@v2
      with:
        release: false
        msystem: ${{matrix.sys}}
        install: >-
          base-devel
          git
          mingw-w64-${{matrix.env}}-toolchain
          mingw-w64-${{matrix.env}}-cmake
          mingw-w64-${{matrix.env}}-ninja
          mingw-w64-${{matrix.env}}-boost
          mingw-w64-${{matrix.env}}-iso-codes
          mingw-w64-${{matrix.env}}-json-c
          mingw-w64-${{matrix.env}}-gettext
          mingw-w64-${{matrix.env}}-nsis

    - name: Install Qt6
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.8.*
        host: windows
        target: desktop
        arch: win64_mingw
        archives: qtbase qttools MinGW
        tools: tools_mingw1310
        add-tools-to-path: true
        cache: true

    # MSYS2 Git assumes CRLF by default
    - name: Configure Git
      run: |
        git config --global core.autocrlf true
        echo "GIT_DESCRIBE=$(git describe --always --dirty)" >> $GITHUB_ENV

    # Build using Qt toolchain because it will be packaged with Qt toolchain's runtime
    - name: Configure Qt toolchain path
      run: echo "TOOLCHAIN_PATH=$(cygpath -u '${{ env.IQTA_TOOLS }}')/mingw1310_64/bin" >> $GITHUB_ENV

    - name: Configure CMake
      run: |
        cmake -G Ninja -B build \
          -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}" \
          -DCMAKE_C_COMPILER="${{ env.TOOLCHAIN_PATH }}/gcc.exe" \
          -DCMAKE_CXX_COMPILER="${{ env.TOOLCHAIN_PATH }}/g++.exe" \
          -DBUILD_SHARED_LIBS=YES \
          -DFETCH_MBEDTLS=YES \
          -DFETCH_ARGP=YES \
          -DBUILD_EMV_DECODE=YES \
          -DBUILD_EMV_TOOL=YES \
          -DBUILD_EMV_VIEWER=YES \
          -DBUILD_WIN_STANDALONE=YES
      # CMake will only accept Windows paths if they are environment variables, not CMake command line cache entries
      env:
        CMAKE_PREFIX_PATH: ${{ env.QT_ROOT_DIR }}

    - name: Build
      run: cmake --build build -j 4

    - name: Test
      run: ctest --test-dir build -j 4 --output-on-failure

    - name: Package
      run: cmake --build build --target package

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: emv-utils-${{ env.GIT_DESCRIBE }}-windows
        path: |
            build/emv-utils-*.tar.gz
            build/emv-utils-*.exe
        if-no-files-found: error

    - name: Upload build directory if failed
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: emv-utils-${{ env.GIT_DESCRIBE }}-windows-build
        path: ./
        if-no-files-found: error
